{% set name = "scikit-survival" %}
{% set version = "0.19.0.post1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/scikit-survival-{{ version }}.tar.gz
  sha256: 5018540a9457c9de602f169fdfcc01511a360c8a1480c9913a88061776f05899

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<38]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
  host:
    - cython
    - numpy
    - pip
    - scikit-learn >=1.1.2,<1.2
    - packaging
    - python
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scikit-learn >=1.1.2,<1.2
    - ecos
    - joblib
    - numexpr
    - osqp !=0.6.0,!=0.6.1
    - pandas >=1.0.5
    - scipy >=1.3.2

test:
  imports:
    - sksurv
    - sksurv.datasets
    - sksurv.ensemble
    - sksurv.io
    - sksurv.kernels
    - sksurv.linear_model
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sebp/scikit-survival
  summary: Survival analysis built on top of scikit-learn
  license: GPL-3.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - janjagusch
    - xhochy
